[package]
name = "composition_credits"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
miso = { local = "../../../misonetwork/protocol" }
partyos = { local = "../../../misonetwork/party", rename-from = "miso_party" }
miso_credit = { local = "../../../misonetwork/credit" }
