[package]
name = "release_genre"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
genre = { git = "https://github.com/misonetwork/genre.git", rev = "b94b11e31e0b0b8b30369a512c01aaa8f2bb5efa" }
miso = { git = "https://github.com/misonetwork/protocol.git", rev = "ecb3da52c14912e257f00b30185c598e92ffc5e3" }
per_track = { git = "https://github.com/misonetwork/per-track.git", rev = "0bc57928c73b911cfcde41abaf3f5973e64e1708" }
