[package]
name = "release_cover_art"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
cover_art = { local = "../lib/cover_art" }
miso = { local = "../../miso-protocol" }
per_track = { local = "../lib/per_track" }
