[package]
name = "recording_credits"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
miso = { git = "https://github.com/misonetwork/protocol.git", rev = "ecb3da52c14912e257f00b30185c598e92ffc5e3" }
partyos = { git = "https://github.com/misonetwork/party.git", rev = "0127a1501f56461a9345aab040dfde8c62a81dd0", rename-from = "miso_party" }
miso_credit = { git = "https://github.com/misonetwork/credit.git", rev = "76a1afc76bd4231ce491400ac01cf3264614b416" }
