[package]
name = "release_dsp_link"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
miso = { git = "https://github.com/misonetwork/protocol.git", rev = "7c13e40a2613fd01a42353c2e98e614cfa671449" }
per_track = { git = "https://github.com/misonetwork/per-track.git", rev = "cae740f152f52edf87940b043cbcaeb6dbb835e0" }
