[package]
name = "composition_recording_stake"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
miso = { local = "../../../misonetwork/protocol" }
hikida = { git = "https://github.com/unconfirmedlabs/hikida.git", rev = "e88c6fa88348bc2764823cf3666d7ca5e08b2f4f" }
royalty_pool = { local = "../lib/royalty_pool" }
